configfile: "config/config.yaml"
SAMPLES = list(config["samples"].keys())
THREADS = config["analysis"]["threads"]

rule all:
    input:
        expand("results/qc/{sample}_R1_fastqc.html", sample=SAMPLES),
        "results/multiqc/multiqc_report.html",
        expand("results/bam/{sample}.bam.bai", sample=SAMPLES),
        "results/counts/counts.txt",
        "results/report/report.html"

rule download_fastq:
    output:
        r1 = "data/raw/{sample}_R1.fastq.gz",
        r2 = "data/raw/{sample}_R2.fastq.gz"
    params:
        srr = lambda wc: config["samples"][wc.sample]["srr"]
    threads: 2
    shell:
        """
        prefetch {params.srr} -O data/raw/
        fastq-dump data/raw/{params.srr}/{params.srr}.sra \
            --outdir data/raw/ --split-files --gzip \
            -X 5000000
        rm -rf data/raw/{params.srr}/
        mv data/raw/{params.srr}_1.fastq.gz {output.r1}
        mv data/raw/{params.srr}_2.fastq.gz {output.r2}
        """

rule fastqc:
    input:
        r1 = "data/raw/{sample}_R1.fastq.gz",
        r2 = "data/raw/{sample}_R2.fastq.gz"
    output:
        "results/qc/{sample}_R1_fastqc.html",
        "results/qc/{sample}_R2_fastqc.html"
    threads: 2
    shell:
        "fastqc {input.r1} {input.r2} -o results/qc/ -t {threads}"

rule trim:
    input:
        r1 = "data/raw/{sample}_R1.fastq.gz",
        r2 = "data/raw/{sample}_R2.fastq.gz"
    output:
        r1   = "results/trimmed/{sample}_R1.fastq.gz",
        r2   = "results/trimmed/{sample}_R2.fastq.gz",
        json = "results/qc/{sample}_fastp.json"
    threads: THREADS
    shell:
        "fastp -i {input.r1} -I {input.r2} "
        "-o {output.r1} -O {output.r2} "
        "--detect_adapter_for_pe "
        "--thread {threads} "
        "-j {output.json}"

rule multiqc:
    input:
        expand("results/qc/{sample}_R1_fastqc.html", sample=SAMPLES),
        expand("results/qc/{sample}_fastp.json", sample=SAMPLES)
    output:
        "results/multiqc/multiqc_report.html"
    shell:
        "multiqc results/qc/ -o results/multiqc/ --force"

rule hisat2_index:
    input:
        fasta = config["genome"]["fasta"]
    output:
        touch("genome/hisat2_index/.done")
    threads: THREADS
    shell:
        "hisat2-build -p {threads} {input.fasta} genome/hisat2_index/genome"

rule align:
    input:
        r1    = "results/trimmed/{sample}_R1.fastq.gz",
        r2    = "results/trimmed/{sample}_R2.fastq.gz",
        index = "genome/hisat2_index/.done"
    output:
        bam = "results/bam/{sample}.bam"
    threads: THREADS
    shell:
        "hisat2 -x genome/hisat2_index/genome "
        "-1 {input.r1} -2 {input.r2} "
        "-p {threads} --dta "
        "| samtools sort -@ {threads} -o {output.bam}"

rule index_bam:
    input:  "results/bam/{sample}.bam"
    output: "results/bam/{sample}.bam.bai"
    shell:  "samtools index {input}"

rule featurecounts:
    input:
        bams = expand("results/bam/{sample}.bam", sample=SAMPLES),
        gtf  = config["genome"]["gtf"]
    output:
        "results/counts/counts.txt"
    threads: THREADS
    shell:
        "featureCounts -T {threads} -p "
        "-a {input.gtf} "
        "-o {output} "
        "{input.bams}"

rule deseq2_report:
    input:
        counts = "results/counts/counts.txt"
    output:
        "results/report/report.html"
    shell:
        "Rscript -e \""
        "rmarkdown::render("
        "'scripts/report.Rmd',"
        "output_file='../results/report/report.html',"
        "knit_root_dir=getwd())\""
