genome:
  species: "human"
  assembly: "GRCh38"
  fasta: "genome/GRCh38.fa"
  gtf:   "genome/GRCh38.gtf"
  index: "genome/hisat2_index/genome"

samples:
  tumor_1:  {srr: "SRR6671104", condition: "tumor"}
  tumor_2:  {srr: "SRR6671105", condition: "tumor"}
  tumor_3:  {srr: "SRR6671106", condition: "tumor"}
  normal_1: {srr: "SRR6671114", condition: "normal"}
  normal_2: {srr: "SRR6671115", condition: "normal"}
  normal_3: {srr: "SRR6671116", condition: "normal"}

analysis:
  reference_condition: "normal"
  treatment_condition: "tumor"
  padj_cutoff: 0.05
  lfc_cutoff: 1.0
  threads: 4

fastp:
  min_length: 36
  quality: 20

featurecounts:
  strand: 0
  paired: true
